//used in dev only
#if DEBUG

using System;
using System.Collections.Generic;
using System.Text;

namespace Celeste.Mod.GooberHelper.Options {
    public static partial class OptionsManager {
        //puts it on your clipboard
        public static void GenerateLuaOptions() {
            var builder = new StringBuilder();

            builder.AppendLine(
                """
                local headers = require("mods").requireFromPlugin("libraries.goober.headers")

                -- this file is automatically generated with Options/OptionsManager.LuaGenerator.cs
                -- 
                -- please dont try to tweak it yourself when adding an option; open celesterepl or
                -- the c# debug console mod idr what it was called and execute the following line:
                -- Celeste.Mod.GooberHelper.OptionsManager.GenerateLuaOptions()
                -- 
                -- after that, paste the new content on your clipboard into this file
                
                return {
                """
            );
            
            var justAppendedHeader = true;

            foreach(var category in Enum.GetValues<OptionCategory>()) {
                if(!justAppendedHeader)
                    builder.AppendLine();
                
                builder.AppendLine($"\theaders.categoryHeader(\"{category}\"),");

                justAppendedHeader = true;

                foreach(var option in CategoryToOptions[category]) {
                    var optionInstance = OptionToInstance[option];
                    var headGroup = optionInstance.HeadGroup;

                    if(headGroup != OptionGroup.None) {
                        if(!justAppendedHeader)
                            builder.AppendLine();
                        
                        builder.AppendLine($"\theaders.groupHeader(\"{headGroup}\"),");
                    }

                    builder.Append($"\t\"{option}");

                    justAppendedHeader = false;
                
                    //boolean handling
                    if(optionInstance.Type == OptionType.Boolean)
                        goto endLine;

                    var possibleTypes = new List<string>();

                    //other stuff handling
                    if(optionInstance.Type == OptionType.Float)
                        possibleTypes.Add("number");

                    if(optionInstance.EnumType is Type enumType)
                        foreach(var enumName in Enum.GetNames(enumType))
                            possibleTypes.Add(enumName);
                    
                    builder.Append($": [{string.Join("|", possibleTypes)}]");

                    //end
                    endLine:
                    builder.Append("\",\n");
                }
            }

            //remove the stray ,
            builder.Length -= 2;
            builder.Append(",\n}");

            TextInput.SetClipboardText(builder.ToString());
        }
    }
}

#endif